---
  - name: DEPLOY SNMP CONFIG
    hosts: ios
    connection: network_cli
    no_log: false
    gather_facts: false

    tasks:
      - name: DEPLOY_SNMP_COMMANDS_WITHIN_PLAYBOOK
        ios_config:
          commands:
            - snmp-server community Public123 RO
            - snmp-server community networktocode RO
            - snmp-server community provate123 RW
            - snmp-server location TEST_ENV
            - snmp-server contact ACH

  ##  vars_prompt:
  ##    - name: username
  ##      prompt: "Username"
  ##      private: no
  ##    - name: password
  ##     prompt: "Password"
        
   ##       username: '{{ username }}'
   ##       password: '{{ password }}'
